import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// or `v1X-appRouter` if you are using Next.js v1X
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import './globals.css';
import { ThemeProvider } from '@mui/material';
import theme from '@/constants/theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
